apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fancycrets.socalswami17.io
spec:
  group: socalswami17.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretA:
                  type: string
                secretB:
                  type: string
  scope: Namespaced
  names:
    plural: fancycrets
    singular: fancycret
    kind: Fancycret
    shortNames:
      - fcycret