---
apiVersion: v1
kind: Secret
metadata:
  name: common
type: opaque
data:
  commonKey: Y29tbW9uVmFsdWU=

---
apiVersion: v1
kind: Secret
metadata:
  name: env1
type: opaque
data:
  envKey: ZW52MVZhbHVl

---
apiVersion: v1
kind: Secret
metadata:
  name: env1-swamibot
  annotations: {}
    #"fancycrets.secretSource.0": "common"
    #"fancycrets.secretSource.1": "env1"
    #"fancycrets.secretFormat.COMMON_TOKEN": "{commonKey}"
    #"fancycrets.secretFormat.ENV_TOKEN": "https://external-service.test/?static_token={envKey}"
type: opaque
data:
  INIT_KEY: aW5pdFZhbHVl
